baseURL = 'https://kodin.cc'
languageCode = 'en-us'
title = "Kodin's Tower"

[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[params]
custom_css = ["css/styles.css"]

[taxonomies]
  blog_tags = 'blog/tags'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Links'
    pageRef = '/links'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/aboutme'
    weight = 30
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 50

