baseURL = 'https://kodin.cc'
languageCode = 'en-us'
title = "Kodin's Tower"

[outputs]
  home     = ['html']
  section  = ['html', 'rss']
  taxonomy = ['html']
  term     = ['html', 'rss']

[params]
custom_css = ["css/styles.css"]

[taxonomies]
  blog_tags = 'blog/tags'
