baseURL = 'https://koldinium.com'
languageCode = 'en-us'
title = "Koldinium's Tower"

[outputs]
  home     = ['html']
  section  = ['html', 'rss']
  taxonomy = ['html']
  term     = ['html', 'rss']

[params]
custom_css = ["css/styles.css"]

[minify]
disableXML = true

[taxonomies]
  blog_tags = 'blog/tags'
